{"Timestamp":"2020-01-27T19:22:49.2310523+03:00","Level":"Error","MessageTemplate":"Ошибка при обработке запроса {0}","RenderedMessage":"Ошибка при обработке запроса \"/Home/ThrowException\"","Exception":"System.ApplicationException: Тестовая ошибка в программе\r\n   at WebStore.Controllers.HomeController.ThrowException() in C:\\Users\\shmac\\Documents\\!GB\\asp.net-core-2\\src\\WebStore\\UI\\WebStore\\Controllers\\HomeController.cs:line 19\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at WebStore.Infrastructure.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext Context) in C:\\Users\\shmac\\Documents\\!GB\\asp.net-core-2\\src\\WebStore\\UI\\WebStore\\Infrastructure\\Middleware\\ErrorHandlingMiddleware.cs:line 25","Properties":{"0":"/Home/ThrowException","SourceContext":"WebStore.Infrastructure.Middleware.ErrorHandlingMiddleware","RequestId":"0HLT38KC34Q31:00000002","RequestPath":"/Home/ThrowException","CorrelationId":null,"ConnectionId":"0HLT38KC34Q31","Application":"Sample"}},{"Timestamp":"2020-01-27T19:22:49.7384376+03:00","Level":"Error","MessageTemplate":"An unhandled exception has occurred while executing the request.","RenderedMessage":"An unhandled exception has occurred while executing the request.","Exception":"System.ApplicationException: Тестовая ошибка в программе\r\n   at WebStore.Controllers.HomeController.ThrowException() in C:\\Users\\shmac\\Documents\\!GB\\asp.net-core-2\\src\\WebStore\\UI\\WebStore\\Controllers\\HomeController.cs:line 19\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at WebStore.Infrastructure.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext Context) in C:\\Users\\shmac\\Documents\\!GB\\asp.net-core-2\\src\\WebStore\\UI\\WebStore\\Infrastructure\\Middleware\\ErrorHandlingMiddleware.cs:line 25\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.ExecuteWithFilter(IHttpSocketAdapter injectScriptSocket, String requestId, HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","Properties":{"EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"0HLT38KC34Q31:00000002","RequestPath":"/Home/ThrowException","CorrelationId":null,"ConnectionId":"0HLT38KC34Q31","Application":"Sample"}},